-- select recent trades 
-- SELECT ADDRESS FROM TRADES WHERE BLOCK_HEIGHT>730000 GROUP BY ADDRESS;

-- -- get address balance in usd by grouping by address and suming amount based on case denom
-- SELECT ADDRESS , SUM(CASE 
-- WHEN DENOM === 'swth' THEN AMOUNT * 0.00000005
-- WHEN DENOM === 'usdc' THEN AMOUNT * 0.000001
-- WHEN DENOM === 'tmz' THEN AMOUNT * 0.003
-- END
-- ) AS TOTAL_USD FROM BALANCES WHERE TOTAL_USD >=500 GROUP BY ADDRESS;

-- Final
SELECT ADDRESS FROM TRADES WHERE BLOCK_HEIGHT>>730000 GROUP BY ADDRESS INNER JOIN (SELECT ADDRESS , SUM(CASE 
WHEN DENOM === 'swth' THEN AMOUNT * 0.00000005
WHEN DENOM === 'usdc' THEN AMOUNT * 0.000001
WHEN DENOM === 'tmz' THEN AMOUNT * 0.003
END
) AS TOTAL_USD FROM BALANCES WHERE TOTAL_USD >=500 GROUP BY ADDRESS) AS WALLET ON WALLET.ADDRESS = TRADE.ADDRESS;